# Generated by Django 4.2.7 on 2024-01-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="details",
            fields=[
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                (
                    "username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("phone", models.IntegerField()),
                ("employment", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=100)),
                ("concern", models.CharField(max_length=100)),
                ("Test_Result", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "details",
            },
        ),
    ]
