# Generated by Django 4.2.7 on 2024-01-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="password",
            field=models.CharField(default="default_password", max_length=100),
        ),
    ]
