# Generated by Django 4.2.7 on 2024-02-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0005_alter_artwork_table_alter_comment_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("employment", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=100)),
                ("concern", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("qualification", models.CharField(max_length=100)),
                ("experience", models.IntegerField()),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="artwork",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DAST_app.patient"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="DAST_app.therapist"
            ),
        ),
        migrations.DeleteModel(
            name="details",
        ),
    ]
