# Generated by Django 4.2.7 on 2024-02-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0006_patient_therapist_alter_artwork_user_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="patient",
            table="Patient",
        ),
        migrations.AlterModelTable(
            name="therapist",
            table="Therapist",
        ),
    ]
