# Generated by Django 4.2.7 on 2024-03-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "DAST_app",
            "0009_chat_remove_comment_artwork_remove_comment_therapist_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chat",
            table="Chat",
        ),
    ]
