# Generated by Django 4.2.7 on 2024-03-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0010_alter_chat_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PDFbooks",
        ),
    ]
