# Generated by Django 4.2.7 on 2024-03-07 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0011_delete_pdfbooks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artwork", models.ImageField(upload_to="artwork/")),
                ("comments", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DAST_app.patient",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DAST_app.therapist",
                    ),
                ),
            ],
            options={
                "db_table": "ArtConsultation",
            },
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
