# Generated by Django 4.2.7 on 2024-03-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0012_artconsultation_delete_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artconsultation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_consultations",
                to="DAST_app.patient",
                to_field="username",
            ),
        ),
        migrations.AlterField(
            model_name="artconsultation",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist_consultations",
                to="DAST_app.therapist",
                to_field="username",
            ),
        ),
    ]
