# Generated by Django 4.2.7 on 2024-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0013_alter_artconsultation_patient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artconsultation",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="artconsultation",
            name="therapist",
        ),
        migrations.AddField(
            model_name="artconsultation",
            name="patient_username",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artconsultation",
            name="therapist_username",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
