# Generated by Django 4.2.7 on 2024-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0015_artconsultation1_delete_artconsultation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_username", models.CharField(max_length=150)),
                ("therapist_username", models.CharField(max_length=150)),
                ("artwork", models.ImageField(upload_to="artwork/")),
                ("comments", models.TextField()),
            ],
            options={
                "db_table": "ArtConsultation",
            },
        ),
        migrations.DeleteModel(
            name="ArtConsultation1",
        ),
    ]
