# Generated by Django 4.2.7 on 2024-03-07 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0016_artconsultation_delete_artconsultation1"),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapistReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="DAST_app.artconsultation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_replies",
                        to="DAST_app.patient",
                        to_field="username",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_replies",
                        to="DAST_app.therapist",
                        to_field="username",
                    ),
                ),
            ],
            options={
                "db_table": "TherapistReply",
            },
        ),
    ]
