# Generated by Django 4.2.7 on 2024-03-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DAST_app", "0017_therapistreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="artconsultation",
            name="therapist_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="TherapistReply",
        ),
    ]
