# Generated by Django 4.2.7 on 2024-04-29 08:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DAST_app', '0019_therapyaccess_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAST_app.patient')),
            ],
            options={
                'db_table': 'Progress',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
